### ISSUE TITLE
since the last updates (iobroker) not working

### ISSUE THREAD

**Issue by totti1171** [mafof/ioBroker.mihome-humidifier#7]
mihome-humidifier.0 | 2020-04-25 20:27:25.449 | error | at processTicksAndRejections (internal/process/task_queues.js:93:5)
-- | -- | -- | --
mihome-humidifier.0 | 2020-04-25 20:27:25.449 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8067:34
mihome-humidifier.0 | 2020-04-25 20:27:25.449 | error | at Adapter.emit (events.js:210:5)
mihome-humidifier.0 | 2020-04-25 20:27:25.449 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.mihome-humidifier/main.js:28:5)
mihome-humidifier.0 | 2020-04-25 20:27:25.449 | error | at main (/opt/iobroker/node_modules/iobroker.mihome-humidifier/main.js:32:5)
mihome-humidifier.0 | 2020-04-25 20:27:25.449 | error | at setNameInstanceAdapter (/opt/iobroker/node_modules/iobroker.mihome-humidifier/main.js:59:21)
mihome-humidifier.0 | 2020-04-25 20:27:25.449 | error | (10124) TypeError: adapter.objects.getObject is not a function
mihome-humidifier.0 | 2020-04-25 20:27:25.446 | error | (10124) uncaught exception: adapter.objects.getObject is not a function

**Comment by totti1171** [comment]
`

mihome-humidifier.0 | 2020-05-01 18:28:51.705 | error | (9266) TypeError: adapter.objects.getObject is not a function at setNameInstanceAdapter (/opt/iobroker/node_modules/iobroker.mihome-humidifier/main.js:59:21) at main (/opt/iobroker/node_module
-- | -- | -- | --
mihome-humidifier.0 | 2020-05-01 18:28:51.700 | error | (9266) uncaught exception: adapter.objects.getObject is not a function

`

**Comment by kenny384** [comment]
Same issue here. Is the developer of this adapter still somehow available?

**Comment by andromedi4** [comment]
I have same issue :( Does anyone have any ideas?

**Comment by Reixi** [comment]
Hey, I have the same problem.

**Comment by tnowak** [comment]
Same issue. Doesn't work on js-controller 3.1.
Had to downgrade to 2.2.9 because of this adapter.

**Comment by Pittini** [comment]
I've made it working again, see my pull request: https://github.com/mafof/ioBroker.mihome-humidifier/pulls

Until the pull request is merged, you can install from my fork at:
https://github.com/Pittini/ioBroker.mihome-humidifier

**Comment by tnowak** [comment]
THANK YOU SO MUCH @Pittini ! Your fork works perfectly!
